<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaaSify.MultiTenant.Application\SaaSify.MultiTenant.Application.csproj" />
    <ProjectReference Include="..\SaaSify.MultiTenant.Infrastructure\SaaSify.MultiTenant.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Configurations\" />
    <Folder Include="Extensions\" />
    <Folder Include="Common\" />
  </ItemGroup>

</Project>
